stages:          # List of stages for jobs, and their order of execution
  - quality

sonarqube:   # This job runs in the quality stage.
  stage: quality
  tags:
    - sonar
  script:
    - echo "Running the sonarqube scanner with gitlab runner"
    - sonar-scanner