// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export { }

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    BaseButton: typeof import('./components/parts/BaseButton.vue')['default']
    Breadcrumbs: typeof import('./components/parts/Breadcrumbs.vue')['default']
    BulletinSectionHeader: typeof import('./components/parts/bulletin/BulletinSectionHeader.vue')['default']
    BulletinSectionHeaderForPost: typeof import('./components/parts/bulletin/BulletinSectionHeaderForPost.vue')['default']
    CautionWindow: typeof import('./components/parts/CautionWindow.vue')['default']
    Check: typeof import('./components/parts/modals/Check.vue')['default']
    Dialog: typeof import('@headlessui/vue')['Dialog']
    DialogPanel: typeof import('@headlessui/vue')['DialogPanel']
    DialogTitle: typeof import('@headlessui/vue')['DialogTitle']
    Empty: typeof import('./components/parts/Empty.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Information: typeof import('./components/parts/modals/Information.vue')['default']
    InputBox: typeof import('./components/parts/InputBox.vue')['default']
    Loading: typeof import('./components/parts/loading.vue')['default']
    LoadingModal: typeof import('./components/parts/modals/LoadingModal.vue')['default']
    MemberEmergency: typeof import('./components/parts/member/MemberEmergency.vue')['default']
    MemberInfo: typeof import('./components/parts/member/MemberInfo.vue')['default']
    MemberOrganization: typeof import('./components/parts/member/MemberOrganization.vue')['default']
    MemberProfile: typeof import('./components/parts/member/MemberProfile.vue')['default']
    MemberSectionHeader: typeof import('./components/parts/member/MemberSectionHeader.vue')['default']
    Menu: typeof import('@headlessui/vue')['Menu']
    MenuButton: typeof import('@headlessui/vue')['MenuButton']
    MenuItem: typeof import('@headlessui/vue')['MenuItem']
    MenuItems: typeof import('@headlessui/vue')['MenuItems']
    Pagination: typeof import('./components/Pagination.vue')['default']
    PostTab: typeof import('./components/parts/PostTab.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectMenus: typeof import('./components/parts/SelectMenus.vue')['default']
    ShowPost: typeof import('./components/parts/ShowPost.vue')['default']
    Switch: typeof import('@headlessui/vue')['Switch']
    SwitchGroup: typeof import('@headlessui/vue')['SwitchGroup']
    SwitchLabel: typeof import('@headlessui/vue')['SwitchLabel']
    Toast: typeof import('./components/parts/Toast.vue')['default']
    ToastNotification: typeof import('./components/ToastNotification.vue')['default']
    TransitionChild: typeof import('@headlessui/vue')['TransitionChild']
    TransitionRoot: typeof import('@headlessui/vue')['TransitionRoot']
    WriteButton: typeof import('./components/parts/WriteButton.vue')['default']
  }
}
