// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    BaseButton: typeof import('./components/parts/BaseButton.vue')['default']
    Breadcrumbs: typeof import('./components/parts/Breadcrumbs.vue')['default']
    BulletinSectionHeader: typeof import('./components/parts/bulletin/BulletinSectionHeader.vue')['default']
    CautionWindow: typeof import('./components/parts/CautionWindow.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    InputBox: typeof import('./components/parts/InputBox.vue')['default']
    Loading: typeof import('./components/parts/loading.vue')['default']
    MemberEmergency: typeof import('./components/parts/member/MemberEmergency.vue')['default']
    MemberInfo: typeof import('./components/parts/member/MemberInfo.vue')['default']
    MemberOrganization: typeof import('./components/parts/member/MemberOrganization.vue')['default']
    MemberProfile: typeof import('./components/parts/member/MemberProfile.vue')['default']
    MemberSectionHeader: typeof import('./components/parts/member/MemberSectionHeader.vue')['default']
    Pagination: typeof import('./components/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectMenus: typeof import('./components/parts/SelectMenus.vue')['default']
    Toast: typeof import('./components/parts/Toast.vue')['default']
    ToastNotification: typeof import('./components/ToastNotification.vue')['default']
  }
}
